version: "3.2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo:mongo-db
    depends_on:
      - mongo
  mongo:
    container_name: mongo-db
    image: mongo
    ports:
      - "27017:27017"